version: "3"
services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal_pass
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - 8050:80
    volumes:
      - ./app:/app
      - ./install:/install
    restart: always
volumes:
  db_data: